### ISSUE TITLE
Frontend Invoice Scheduling

### ISSUE THREAD

**Issue by nakraft** [nakraft/AUTOR#8]
When an invoice is assigned, it should first make sure the employee wouldn't be overworking. Currently no check is being performed.

Backend functioning, frontend is not querying correctly to display the options for scheduling the Services.

**Comment by LeooHsiang** [comment]
![image](https://user-images.githubusercontent.com/40188396/201999010-001388b4-f8de-4cb1-a7d6-d9278896fcf5.png)

**Comment by LeooHsiang** [comment]
Check is implemented to make sure the mechanic doesn't overwork.
